# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoursStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_num', models.DateField()),
                ('character', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
                ('sum_hours', models.IntegerField(default=0)),
                ('hours_already', models.IntegerField(default=0)),
                ('hours_rest', models.IntegerField(default=0)),
            ],
        ),
    ]
