# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0003_hoursdailyclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('try_class_one', models.CharField(default=b'\xe8\x92\x99\xe6\xb0\x8f', max_length=200)),
                ('try_class_one_state', models.CharField(default=b'\xe6\x9c\xaa\xe4\xb8\x8a', max_length=200)),
                ('class_one_teacher', models.CharField(max_length=200)),
                ('try_class_two', models.CharField(default=b'\xe8\x92\x99\xe6\xb0\x8f', max_length=200)),
                ('try_class_two_state', models.CharField(default=b'\xe6\x9c\xaa\xe4\xb8\x8a', max_length=200)),
                ('class_two_teacher', models.CharField(max_length=200)),
            ],
        ),
    ]
