# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0004_trystudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('phone_num', models.CharField(max_length=200)),
                ('character', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=200)),
                ('sum_hours', models.IntegerField(default=0)),
                ('course_type', models.CharField(max_length=200)),
                ('course_frequency', models.CharField(max_length=200)),
                ('hours_already', models.IntegerField(default=0)),
                ('register_date', models.DateField(default=b'2016-11-11')),
            ],
        ),
    ]
