# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managesystem', '0005_coursestudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDailyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default=b'\xe8\x92\x99\xe6\xb0\x8f', max_length=200)),
                ('class_color', models.CharField(default=b'#f39c12', max_length=200)),
                ('consume_date', models.DateField(default=b'2016-11-11')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managesystem.CourseStudent')),
            ],
        ),
    ]
